spring:
  h2:
    console:
      enabled: true
      path: /h2-console
# By default validators are used twice. First we tell spring to validate before passing it to controller, and second time it is validated by Hibernate before the data is persisted to the database.
# Hibernates validation will not be able to inject the repository instance there and so it will give null point exception.
# Since we are handling the validation in the application side and not handling the validation in the database side, lets disable the hibernates validation:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none